### ISSUE TITLE
Reakit v1 roadmap

### ISSUE THREAD

**Issue by diegohaz** [reakit/reakit#345]
Hi guys,

Since last year I've been experimenting with different implementations and APIs for Reakit v1. I just published an alpha version that can be installed via `npm install reakit@next` and put together [this sandbox](https://codesandbox.io/s/8q9n7o0y8) so people can play with it. 

Docs are far from being ready, but you can access pages like https://next.reakit.io/docs/popover, which have some examples.

I want to list here what has been done and what is left.

### Main goals

- [x] **Remove dependency on `styled-components`**
  <details>
    <p>The core package should have only absolutely necessary styles, and those should be inline.</p>
    
    <p><strong>Done:</strong> There's almost zero styles, only `Backdrop`s and `Popover`s have default styles.</p>

    <p>See <a href="https://github.com/reakit/reakit/blob/next/packages/reakit/src/Dialog/DialogBackdrop.tsx"><code>DialogBackdrop</code></a>.</p>
  </details>

- [x] **Empower themes**
  <details>
    <p>Even without a styling mechanism built in the core package, themes should be able to inject styles into Reakit components.</p>

    <p><strong>Done</strong>: Introduced experimental "systems". They can hook into components and change their options and props, which means they can add `style`, `className` etc. The styling approach (CSS in JS, inline style, css files etc.) is up to the system.</p>

    <p>See <a href="https://github.com/reakit/reakit/tree/next/packages/reakit-system-bootstrap"><code>reakit-system-bootstrap</code></a>.</p>
  </details>
  
- [x] **useHooks**
  <details>
    <p>The current containers should be replaced by hooks. Also, the library should expose a hook version for each component as a low-level API.</p>

    <p><strong>Done</strong>: Every component has a hook that returns its props (`Button` -> `useButton`). Components have a very minimal implementation and use their respective hooks underneath.</p>

    See <a href="https://github.com/reakit/reakit/blob/next/packages/reakit/src/Box/Box.ts"><code>Box</code>/<code>useBox</code></a>.
  </details>

- [x] **Focus on accessibility**
  <details>
    <p>The main focus of the library should be accessibility. All components must be in compliance with WAI-ARIA spec.</p>

    <p><strong>Done</strong>: Components now are fully accessible. Some have been renamed to conform to the spec.</p>

    <p>See <a href="https://github.com/reakit/reakit/blob/next/packages/reakit/src/Dialog/Dialog.tsx"><code>Dialog</code></a>.</p>
  </details>

----

The following sections are related to bugs or missing stuff that should be addressed before the official release.

### Branding

- [x] **New logo**
  <details>
    <p><strong>Done</strong>: <a href="https://github.com/reakit/reakit/tree/next/logo">Logo</a> by @leonardoelias</p>
  </details>

- [x] **Thumbnail**
  <details>
    <p>A standard image for use in website's thumbnail, twitter cover etc. I'm thinking on a component showcase in perspective.</p>
  </details>

### Repo

- [x] **Write migration guide**

- [x] **Update `CONTRIBUTING.md`**
  <details>
    <p>With new instructions.</p>
  </details>
  

### Reakit

- [x] **Write prop descriptions**
  <details>
    <p>There's a few props with <code>/** TODO: Description **/</code> in the code.</p>

    <p><strong>Done</strong>: ad742bc0211690b89333cf47889d43284a363926</p>
  </details>

- [x] **Add `aria-description`s for keyboard shortcuts**
  <details>
    <p>Some components like <code>Dialog</code> have keyboard shortcuts that aren't announced by assistive technologies by default, like <kbd>Esc</kbd> to close the dialog.</p>
  </details>
  
- [x] **Improve `Menu`**
  <details>
    <ul>
      <li>Hover should focus menu items.</li>
      <li>Hover should open submenus keeping focus on menu item disclosure.</li>
    </ul>

    <p><strong>Done</strong>: cf7426f0cb35c2ed4a02308cc426d247b3145ad2</p>
  </details>

- [x] **Fix `Dialog`'s outside click when it's on an element inside the disclosure**
  <details>
    <p>The <code>hideOnClickOutside</code> feature of <code>Dialog</code> ignores clicks on <code>DialogDisclosure</code>, since it will hide the dialog anyway. However, clicking on elements inside the <code>DialogDisclosure</code> is still caught and this must be fixed.</p>

    <p><strong>Done</strong>: 93072cb75d742bd9947141274d5127e4e3b6d606</p>
  </details>

- [x] **`as`/`use`**
  <details>
    <p>The <code>use</code> prop introduced in <code>v0.16.0</code> has been rolled back to the <code>as</code> prop. The main reason is that it now behaves the same as in other libraries, accepting a single component, and not an array anymore.</p>

    <p>For composing multiple components, there are now two options:</p>

    1. Render props
    ```jsx
    import { TooltipReference, ToolbarItem, Button } from "reakit";

    <TooltipReference>
      {referenceProps => (
        <ToolbarItem {...referenceProps}>
          {itemProps => (
            <Button {...referenceProps} />
          )}
        </ToolbarItem>
      )}
    </TooltipReference>
    ```

    2. Hooks
    ```jsx
    import { useTooltipReference, useToolbarItem, Button, mergeProps } from "reakit";

    // hooks used internally by TooltipReference and ToolbarItem
    const referenceProps = useTooltipReference();
    const itemProps = useToolbarItem();
    
    <Button {...mergeProps(referenceProps, itemProps)} />
    ```

    Unlike `as`, both approaches work really well. They are only more verbose.

    `as` is full of bugs when used to combine components that share props (like Reakit components), since the first component will "consume" them and not pass to the other one. I guess it should be used only for changing the underlying HTML element. That's probably something that should be addressed in the docs.

    This works in v0 because components don't consume their props. They are passed down and [filtered](https://github.com/reakit/reakit/blob/fd10c8bd0c55f04a36c3b8f7d949c181a8b30d96/packages/reakit/src/Box/Box.ts#L44) in the base component (`Box`). v1 doesn't need this filter.
  </details>

### Website/docs

- [x] **Automatically inject prop types into `README.md` files**
  <details>
    <p>I've been doing some tests <a href="https://github.com/reakit/reakit/blob/288aaa42b26069f1b5560bb6031b15f205adc08b/packages/website/tstest.js">here</a>.</p>

    <p><strong>Done</strong>: 3d3329e8a7b3fdc38ffc326d800e7213bd7768e4</p>
  </details>

- [x] **Write docs**

- [x] **Design home page**
  <details>
    <p>The playground on home should be tabbed, with different "files" and a more realistic example.</p>

    <img src="https://user-images.githubusercontent.com/3068563/55562538-85d19c00-56ca-11e9-81b3-c02aff837c1a.jpg" alt="home page design">
  </details>

- [x] **Design docs page**
  <details>
    <p>Unlike the current website, there should be only one page for documentation, with guide and components in the sidebar.</p>

    <p>There should be a secondary sidebar for content headings and other options (like Edit on GitHub).</p>

    <p>There should be space for "Ads by Carbon"</p>

    <img src="https://user-images.githubusercontent.com/3068563/55562475-5fabfc00-56ca-11e9-9067-55b9a11b5bf3.jpg" alt="docs page design">
  </details>

- [x] **Design playground**
  <details>
    <img src="https://user-images.githubusercontent.com/3068563/55562554-908c3100-56ca-11e9-9ef5-84b018efc12d.jpg" alt="playground design">
  </details>

**Comment by leonardoelias** [comment]
Nice work! I'm really very excited.
I can pick up some tasks.
- [ ]  Design home page
- [ ]  Design docs page
- [ ]  Design playground

**Comment by diegohaz** [comment]
Awesome @leonardoelias. Thank you so much ❤️

I have some thoughts and requirements for those pages. I'm gonna update the issue with them tomorrow.

**Comment by StorytellerCZ** [comment]
Migration guide would be nice too.

**Comment by diegohaz** [comment]
@StorytellerCZ Forgot to include it in the roadmap. Done.

**Comment by diegohaz** [comment]
@leonardoelias Updated the issue with requirements and some drawings.

**Comment by lluia** [comment]
I wow, exciting!! I probably will help with some tasks too; I'll let you know soon 👍

**Comment by leonardoelias** [comment]
Nice @diegohaz!
I'm going to work the weekend, and I'll introduce you to a wireframe.

**Comment by lluia** [comment]
I'll try to continue/finish the accessibility stuff for the PR I made for [`<Menu />`](https://github.com/reakit/reakit/pull/290) 👍🏻

**Comment by StorytellerCZ** [comment]
@lluia Take a look on Reach menu: https://ui.reach.tech/menu-button

**Comment by diegohaz** [comment]
Maybe it's not worth it working on that PR since we already have an accessible Menu in v1 (https://next.reakit.io/docs/menu). Although It needs to be improved as I mentioned in the roadmap. 

Unless we want to have Menu in v0. Then it's better to use that PR.

**Comment by lluia** [comment]
@diegohaz ah I didn't realise we already have a `<Menu />` component in **v1**, should we close my PR then?

**Comment by mattfwood** [comment]
@diegohaz I'd definitely be interested in contributing to:

- [ ] Write prop descriptions
- [ ] Write docs

I know docs obviously involves a lot, but once there's an issue for the new docs I can pick up several components to write docs for.

**Comment by ConneXNL** [comment]
I am looking at @next, wondering how one would implement the fade / slide/ animated features of reactkit's Overlay pre 1.?

Is there a new component that is handling this?

**Comment by diegohaz** [comment]
@ConneXNL There will be a `hasTransition` prop in the next alpha/beta version. Transitions can be implemented by the user via CSS (most of them are pretty simple), or we can build it in a system.

**Comment by ConneXNL** [comment]
@diegohaz Good to know. I was personally struggling with animating out and how to manage that the object stays a little longer to show the hide animation. Using styled components (CSS) to set the transitions seems fine. Outside of reakit I leverage transition groups for these kind of things but I am not sure what the best practice is when using them with reakit.

**Comment by diegohaz** [comment]
@ConneXNL It's released in `reakit@1.0.0-alpha.4`: https://next.reakit.io/docs/hidden/

![image](https://user-images.githubusercontent.com/3068563/57585129-36953d00-74ba-11e9-9377-f8e0d36071dc.png)
